### ISSUE TITLE
Open source

### ISSUE THREAD

**Issue by hotsu0p** [Intelligence-Studio/Intelligence-Studios#4]
Please could you make this mod open source? if you were i would contibute some stuff to it

**Comment by PMulberry** [comment]
Hi,
do you mean  the mod "Ultimate Expansion Mod" or the modpack "Lightning"?
Yours sincerely
PMulberry

**Comment by PMulberry** [comment]
Sorry, I accidentally closed this issue.

**Comment by hotsu0p** [comment]
@PMulberry i mean Ultimate Expansion Mod

**Comment by PMulberry** [comment]
Unfortunately, I don't want this mod to be open source yet. If you told me your ideas, I would credit you on CurseForge and Modrinth. If you wanted to do this, you can contact me on Discord: pmulberry.
